//
//  StaticStocksData.swift
//  goal-folio
//
//  Created by Pratham S on 11/7/25.
//

import Foundation

// Static catalog of commonly followed Stocks.
// Keep this in Core/Models so it’s reusable across features (search, watchlist seed, etc.).
enum StaticStockData {
    static let all: [Stock] = [
        // Mega-cap tech
        Stock(symbol: "AAPL", name: "Apple Inc."),
        Stock(symbol: "MSFT", name: "Microsoft Corporation"),
        Stock(symbol: "GOOGL", name: "Alphabet Inc. Class A"),
        Stock(symbol: "GOOG", name: "Alphabet Inc. Class C"),
        Stock(symbol: "AMZN", name: "Amazon.com, Inc."),
        Stock(symbol: "NVDA", name: "NVIDIA Corporation"),
        Stock(symbol: "META", name: "Meta Platforms, Inc."),
        Stock(symbol: "TSLA", name: "Tesla, Inc."),
        Stock(symbol: "AVGO", name: "Broadcom Inc."),
        Stock(symbol: "TSM", name: "Taiwan Semiconductor Manufacturing Company Limited"),
        Stock(symbol: "NFLX", name: "Netflix, Inc."),
        Stock(symbol: "ADBE", name: "Adobe Inc."),
        Stock(symbol: "CRM", name: "Salesforce, Inc."),
        Stock(symbol: "ORCL", name: "Oracle Corporation"),
        Stock(symbol: "INTC", name: "Intel Corporation"),
        Stock(symbol: "AMD", name: "Advanced Micro Devices, Inc."),
        Stock(symbol: "CSCO", name: "Cisco Systems, Inc."),
        Stock(symbol: "QCOM", name: "QUALCOMM Incorporated"),
        Stock(symbol: "IBM", name: "International Business Machines Corporation"),
        Stock(symbol: "SHOP", name: "Shopify Inc."),
        Stock(symbol: "UBER", name: "Uber Technologies, Inc."),
        Stock(symbol: "LYFT", name: "Lyft, Inc."),
        Stock(symbol: "SNOW", name: "Snowflake Inc."),
        Stock(symbol: "PANW", name: "Palo Alto Networks, Inc."),
        Stock(symbol: "NOW", name: "ServiceNow, Inc."),
        Stock(symbol: "INTU", name: "Intuit Inc."),
        Stock(symbol: "MU", name: "Micron Technology, Inc."),
        Stock(symbol: "AMAT", name: "Applied Materials, Inc."),
        Stock(symbol: "ASML", name: "ASML Holding N.V."),
        Stock(symbol: "TXN", name: "Texas Instruments Incorporated"),
        Stock(symbol: "ADI", name: "Analog Devices, Inc."),
        Stock(symbol: "LRCX", name: "Lam Research Corporation"),
        Stock(symbol: "KLAC", name: "KLA Corporation"),
        Stock(symbol: "NXPI", name: "NXP Semiconductors N.V."),
        Stock(symbol: "MRVL", name: "Marvell Technology, Inc."),
        Stock(symbol: "WDAY", name: "Workday, Inc."),
        Stock(symbol: "ABNB", name: "Airbnb, Inc."),
        Stock(symbol: "DDOG", name: "Datadog, Inc."),
        Stock(symbol: "MDB", name: "MongoDB, Inc."),
        Stock(symbol: "CRWD", name: "CrowdStrike Holdings, Inc."),
        Stock(symbol: "ZS", name: "Zscaler, Inc."),
        Stock(symbol: "NET", name: "Cloudflare, Inc."),
        Stock(symbol: "OKTA", name: "Okta, Inc."),
        Stock(symbol: "DOCU", name: "DocuSign, Inc."),
        Stock(symbol: "TEAM", name: "Atlassian Corporation"),
        Stock(symbol: "TWLO", name: "Twilio Inc."),
        Stock(symbol: "PLTR", name: "Palantir Technologies Inc."),
        Stock(symbol: "U", name: "Unity Software Inc."),
        Stock(symbol: "ROKU", name: "Roku, Inc."),
        Stock(symbol: "SPOT", name: "Spotify Technology S.A."),
        Stock(symbol: "SQ", name: "Block, Inc."),
        Stock(symbol: "PYPL", name: "PayPal Holdings, Inc."),
        Stock(symbol: "AFRM", name: "Affirm Holdings, Inc."),
        Stock(symbol: "COIN", name: "Coinbase Global, Inc."),
        Stock(symbol: "HOOD", name: "Robinhood Markets, Inc."),
        Stock(symbol: "SOFI", name: "SoFi Technologies, Inc."),
        Stock(symbol: "ETSY", name: "Etsy, Inc."),
        Stock(symbol: "PINS", name: "Pinterest, Inc."),
        Stock(symbol: "ZM", name: "Zoom Video Communications, Inc."),
        Stock(symbol: "BIDU", name: "Baidu, Inc."),
        Stock(symbol: "BABA", name: "Alibaba Group Holding Limited"),
        Stock(symbol: "JD", name: "JD.com, Inc."),
        Stock(symbol: "SE", name: "Sea Limited"),
        Stock(symbol: "MELI", name: "MercadoLibre, Inc."),

        // Consumer and retail
        Stock(symbol: "WMT", name: "Walmart Inc."),
        Stock(symbol: "COST", name: "Costco Wholesale Corporation"),
        Stock(symbol: "TGT", name: "Target Corporation"),
        Stock(symbol: "HD", name: "The Home Depot, Inc."),
        Stock(symbol: "LOW", name: "Lowe’s Companies, Inc."),
        Stock(symbol: "NKE", name: "NIKE, Inc."),
        Stock(symbol: "SBUX", name: "Starbucks Corporation"),
        Stock(symbol: "MCD", name: "McDonald’s Corporation"),
        Stock(symbol: "CMG", name: "Chipotle Mexican Grill, Inc."),
        Stock(symbol: "YUM", name: "Yum! Brands, Inc."),
        Stock(symbol: "KO", name: "The Coca-Cola Company"),
        Stock(symbol: "PEP", name: "PepsiCo, Inc."),
        Stock(symbol: "PG", name: "The Procter & Gamble Company"),
        Stock(symbol: "PM", name: "Philip Morris International Inc."),
        Stock(symbol: "MO", name: "Altria Group, Inc."),
        Stock(symbol: "TAP", name: "Molson Coors Beverage Company"),
        Stock(symbol: "DE", name: "Deere & Company"),
        Stock(symbol: "CAT", name: "Caterpillar Inc."),
        Stock(symbol: "F", name: "Ford Motor Company"),
        Stock(symbol: "GM", name: "General Motors Company"),
        Stock(symbol: "RIVN", name: "Rivian Automotive, Inc."),
        Stock(symbol: "LCID", name: "Lucid Group, Inc."),
        Stock(symbol: "NIO", name: "NIO Inc."),

        // Financials
        Stock(symbol: "JPM", name: "JPMorgan Chase & Co."),
        Stock(symbol: "BAC", name: "Bank of America Corporation"),
        Stock(symbol: "WFC", name: "Wells Fargo & Company"),
        Stock(symbol: "C", name: "Citigroup Inc."),
        Stock(symbol: "GS", name: "The Goldman Sachs Group, Inc."),
        Stock(symbol: "MS", name: "Morgan Stanley"),
        Stock(symbol: "BLK", name: "BlackRock, Inc."),
        Stock(symbol: "SCHW", name: "The Charles Schwab Corporation"),
        Stock(symbol: "BX", name: "Blackstone Inc."),
        Stock(symbol: "KKR", name: "KKR & Co. Inc."),
        Stock(symbol: "V", name: "Visa Inc."),
        Stock(symbol: "MA", name: "Mastercard Incorporated"),
        Stock(symbol: "AXP", name: "American Express Company"),
        Stock(symbol: "BRK.B", name: "Berkshire Hathaway Inc. Class B"),
        Stock(symbol: "BRK.A", name: "Berkshire Hathaway Inc. Class A"),

        // Healthcare and pharma
        Stock(symbol: "UNH", name: "UnitedHealth Group Incorporated"),
        Stock(symbol: "JNJ", name: "Johnson & Johnson"),
        Stock(symbol: "PFE", name: "Pfizer Inc."),
        Stock(symbol: "MRK", name: "Merck & Co., Inc."),
        Stock(symbol: "ABBV", name: "AbbVie Inc."),
        Stock(symbol: "AMGN", name: "Amgen Inc."),
        Stock(symbol: "LLY", name: "Eli Lilly and Company"),
        Stock(symbol: "BMY", name: "Bristol-Myers Squibb Company"),
        Stock(symbol: "GILD", name: "Gilead Sciences, Inc."),
        Stock(symbol: "ISRG", name: "Intuitive Surgical, Inc."),
        Stock(symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated"),
        Stock(symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc."),
        Stock(symbol: "CVS", name: "CVS Health Corporation"),
        Stock(symbol: "CI", name: "The Cigna Group"),
        Stock(symbol: "HUM", name: "Humana Inc."),
        Stock(symbol: "ZBH", name: "Zimmer Biomet Holdings, Inc."),

        // Energy and materials
        Stock(symbol: "XOM", name: "Exxon Mobil Corporation"),
        Stock(symbol: "CVX", name: "Chevron Corporation"),
        Stock(symbol: "COP", name: "ConocoPhillips"),
        Stock(symbol: "SLB", name: "Schlumberger Limited"),
        Stock(symbol: "EOG", name: "EOG Resources, Inc."),
        Stock(symbol: "PXD", name: "Pioneer Natural Resources Company"),
        Stock(symbol: "OXY", name: "Occidental Petroleum Corporation"),
        Stock(symbol: "BP", name: "BP p.l.c."),
        Stock(symbol: "SHEL", name: "Shell plc"),
        Stock(symbol: "TOT", name: "TotalEnergies SE"),
        Stock(symbol: "LIN", name: "Linde plc"),
        Stock(symbol: "APD", name: "Air Products and Chemicals, Inc."),
        Stock(symbol: "NEM", name: "Newmont Corporation"),
        Stock(symbol: "FCX", name: "Freeport-McMoRan Inc."),
        Stock(symbol: "RIO", name: "Rio Tinto Group"),
        Stock(symbol: "BHP", name: "BHP Group Limited"),

        // Industrials and aerospace/defense
        Stock(symbol: "GE", name: "General Electric Company"),
        Stock(symbol: "HON", name: "Honeywell International Inc."),
        Stock(symbol: "MMM", name: "3M Company"),
        Stock(symbol: "BA", name: "The Boeing Company"),
        Stock(symbol: "LMT", name: "Lockheed Martin Corporation"),
        Stock(symbol: "NOC", name: "Northrop Grumman Corporation"),
        Stock(symbol: "RTX", name: "RTX Corporation"),
        Stock(symbol: "GD", name: "General Dynamics Corporation"),
        Stock(symbol: "CAT", name: "Caterpillar Inc."),
        Stock(symbol: "DE", name: "Deere & Company"),
        Stock(symbol: "ETN", name: "Eaton Corporation plc"),
        Stock(symbol: "PH", name: "Parker-Hannifin Corporation"),
        Stock(symbol: "EMR", name: "Emerson Electric Co."),
        Stock(symbol: "UPS", name: "United Parcel Service, Inc."),
        Stock(symbol: "FDX", name: "FedEx Corporation"),

        // Utilities and telecom
        Stock(symbol: "NEE", name: "NextEra Energy, Inc."),
        Stock(symbol: "DUK", name: "Duke Energy Corporation"),
        Stock(symbol: "SO", name: "The Southern Company"),
        Stock(symbol: "D", name: "Dominion Energy, Inc."),
        Stock(symbol: "AEP", name: "American Electric Power Company, Inc."),
        Stock(symbol: "VZ", name: "Verizon Communications Inc."),
        Stock(symbol: "T", name: "AT&T Inc."),
        Stock(symbol: "TMUS", name: "T-Mobile US, Inc."),
        Stock(symbol: "CMCSA", name: "Comcast Corporation"),
        Stock(symbol: "CHTR", name: "Charter Communications, Inc."),

        // REITs
        Stock(symbol: "PLD", name: "Prologis, Inc."),
        Stock(symbol: "AMT", name: "American Tower Corporation"),
        Stock(symbol: "CCI", name: "Crown Castle Inc."),
        Stock(symbol: "EQIX", name: "Equinix, Inc."),
        Stock(symbol: "O", name: "Realty Income Corporation"),
        Stock(symbol: "SPG", name: "Simon Property Group, Inc."),

        // Media and entertainment
        Stock(symbol: "DIS", name: "The Walt Disney Company"),
        Stock(symbol: "WBD", name: "Warner Bros. Discovery, Inc."),
        Stock(symbol: "PARA", name: "Paramount Global"),
        Stock(symbol: "FOX", name: "Fox Corporation Class B"),
        Stock(symbol: "FOXA", name: "Fox Corporation Class A"),
        Stock(symbol: "SONY", name: "Sony Group Corporation"),
        Stock(symbol: "TME", name: "Tencent Music Entertainment Group"),

        // Software/SaaS extras
        Stock(symbol: "SAP", name: "SAP SE"),
        Stock(symbol: "ADSK", name: "Autodesk, Inc."),
        Stock(symbol: "ANSS", name: "ANSYS, Inc."),
        Stock(symbol: "FTNT", name: "Fortinet, Inc."),
        Stock(symbol: "SPLK", name: "Splunk Inc."),
        Stock(symbol: "ZS", name: "Zscaler, Inc."),
        Stock(symbol: "DDOG", name: "Datadog, Inc."),
        Stock(symbol: "HUBS", name: "HubSpot, Inc."),
        Stock(symbol: "PAYC", name: "Paycom Software, Inc."),
        Stock(symbol: "TYL", name: "Tyler Technologies, Inc."),
        Stock(symbol: "CDNS", name: "Cadence Design Systems, Inc."),
        Stock(symbol: "SNPS", name: "Synopsys, Inc."),

        // ETFs (useful for testing/search too)
        Stock(symbol: "SPY", name: "SPDR S&P 500 ETF Trust"),
        Stock(symbol: "VOO", name: "Vanguard S&P 500 ETF"),
        Stock(symbol: "IVV", name: "iShares Core S&P 500 ETF"),
        Stock(symbol: "QQQ", name: "Invesco QQQ Trust"),
        Stock(symbol: "VTI", name: "Vanguard Total Stock Market ETF"),
        Stock(symbol: "IWM", name: "iShares Russell 2000 ETF"),
        Stock(symbol: "EFA", name: "iShares MSCI EAFE ETF"),
        Stock(symbol: "EEM", name: "iShares MSCI Emerging Markets ETF"),
        Stock(symbol: "XLK", name: "Technology Select Sector SPDR Fund"),
        Stock(symbol: "XLF", name: "Financial Select Sector SPDR Fund"),
        Stock(symbol: "XLE", name: "Energy Select Sector SPDR Fund"),
        Stock(symbol: "XLV", name: "Health Care Select Sector SPDR Fund"),
        Stock(symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund"),
        Stock(symbol: "XLP", name: "Consumer Staples Select Sector SPDR Fund"),
        Stock(symbol: "XLI", name: "Industrial Select Sector SPDR Fund"),
        Stock(symbol: "XLU", name: "Utilities Select Sector SPDR Fund"),
        Stock(symbol: "XLRE", name: "Real Estate Select Sector SPDR Fund"),
        Stock(symbol: "ARKK", name: "ARK Innovation ETF"),
        Stock(symbol: "SMH", name: "VanEck Semiconductor ETF"),
        Stock(symbol: "SOXX", name: "iShares Semiconductor ETF")
    ]
}
